### ISSUE TITLE
Weird search results issue

### ISSUE THREAD

**Issue by colmtroy** [WebDevStudios/wp-search-with-algolia#114]
**Describe the bug**
Search results don't match those returned by Aloglia when searching the index directly

**To Reproduce**
1. Go to https://xeroshoes.com/?s=prio
2. Observe that the first result for the search term "prio" is a different product (terraflex)

**Expected behavior**
When searching the index directly in Algolia we see "Prio - Kids" is the first result
https://i.imgur.com/tXJexo1.png

This is also what appears via the autocomplete
https://i.imgur.com/0mLsCxl.png

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS Catalina - 10.15.3
 - Browser - Chrome 
 - Version - 87

**Additional context**
Using 1.6.0 of the plugin
I'm also filtering algolia_searchable_post_types to only include products - but this doesn't seem to impact the order of items per se.

**Comment by richaber** [comment]
Howdy @colmtroy,

That is unexpected indeed.

It appears you are using the PHP backed search, which modifies the WP_Query when a search is performed.

Debugging that from here could be difficult, depending on what other components, outside of WPSWA, could potentially be affecting the search template, search results, or the search WP_Query, such as the theme itself, other plugins, or custom code.

Notably, a search for "terraflex" (https://xeroshoes.com/?s=terraflex) appears to reveal more information about the issue, more so than a search for "prio" does.
 
![xeroshoes com__s=terraflex](https://user-images.githubusercontent.com/5407441/103100400-f8d62100-45d7-11eb-9341-b0e2300a69c1.png)

The keyword highlighting in the "terraflex" search results is inconsistent, which implies that something other than WPSWA itself might be affecting what posts are displayed in the search results.

Every instance of the search term "terraflex" in both the titles and content should be highlighted, as that is the expected behavior from WPSWA without some custom code.

Yet the first result that contains the keyword, "Terraflex - Men (Clearance)", does not have "terraflex" highlighted in either the Title or the Content. Subsequent results that have the keyword after that _do_ have the expected highlighting.

The second clue that a component outside of WPSWA is affecting the search, comes from that same "Terraflex - Men (Clearance)" result, which uses the WordPress style ellipses surrounded by square brackets `[…]` to indicate that there is more text.

The subsequent results that have the keyword highlighting, use _only_ an ellipses `…` to indicate that there is more text, which is the expected WPSWA behavior.

I believe the above point to an issue outside of WPSWA's control, and you may wish to try some "standard" debug practices to pinpoint the source or sources of the issue.

I would advise debugging in a local or staging environment, rather than on a live production environment.

Test using the instantsearch.js option to power the search results, rather than the PHP option.
Test using a "default" Twenty* theme to see if the theme itself might be the source of the issue.
Test removing any custom code that might in some way affect search, WP_Query, or Algolia.
Test deactivating other plugins, to see if one of those might be an issue, especially if they are search related or affect WP_Query in some way.

I hope this information helps.
