### ISSUE TITLE
Highlight results from the post tags. 

### ISSUE THREAD

**Issue by kshirodpatel** [WebDevStudios/wp-search-with-algolia#115]
Hi,
How to make  _highlightResult from the matching post tags? In my case I am getting the matching post tags in a plain text. No em tags are being added to the tags. I have tried this way 
`{{{ data._highlightResult.taxonomies.post_tag.value }}}` but its not working.

Can someone tell me what exactly needs to be done to highlight matching post tags?

**Comment by tw2113** [comment]
@kshirodpatel out of curiosity, is this still and issue for you? or did you get things figured out?

**Comment by tw2113** [comment]
Based on some extra testing, I'm suspecting that `data._highlightResult.taxonomies.post_tag` was an array and not a single value and thus not the correct way to attempt showing the highlight.

Chances are that the tag data would need to be output as part of the hit template for either autocomplete or instantsearch, and when doing that, use the `data._highlightResult` version so that if it is a match, it'd have the extra markup.

This example would output just the first in the array, and include the html for highlighting, if it is a match

```
{{{ data._highlightResult.taxonomies.post_tag[0].value }}}
```

Closing as a non bug with the core plugin at the moment.
