### ISSUE TITLE
"Uncaught ReferenceError: algoliasearch is not defined" after upgrading to 2.0.0

### ISSUE THREAD

**Issue by amrutadotorg** [WebDevStudios/wp-search-with-algolia#165]
Hi, after upgrading the plugin to 2.0.0
In the console I'm getting the error "_Uncaught ReferenceError: algoliasearch is not defined_"
my page is www.amruta.org
I'm using default _instantsearch.php_ template.

If possible please guide how to fix the issue.

Option _Use Algolia in the backend_ works fine.

**Comment by amrutadotorg** [comment]
I'm not sure if my solution is a proper one, but following the instruction on 
https://www.algolia.com/doc/guides/building-search-ui/installation/js/
I added:
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.5.1/dist/algoliasearch-lite.umd.js" integrity="sha256-EXPXz4W6pQgfYY3yTpnDa3OH8/EPn16ciVsPQ/ypsjk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.8.3/dist/instantsearch.production.min.js" integrity="sha256-LAGhRRdtVoD6RLo2qDQsU2mp+XVSciKRC8XPOBWmofM=" crossorigin="anonymous"></script>

to the head, which solved the issue.

**Comment by uptimizt** [comment]
I have the same problem

**Comment by uptimizt** [comment]
there is a problem with the condition for the load scripts.
if we use only search page without autocomplete - we get this error.
Algolia_Template_Loader::enqueue_autocomplete_scripts() - started only if enable autocomplete.
but the script for the search page is loaded in the same place

**Comment by richaber** [comment]
I have not encountered this in either my local development environment, nor on my own personal blog where I run WPSWA as a "remote" testing environment to ensure that the zip delivered from WPORG functions as expected.

My local development environment is running PHP 8, WordPress 5.8, and the Twenty Twenty-One theme.

My personal blog is running PHP 7.4.21, WordPress 5.8, and the Twenty Twenty theme.

I have no customizations in either environment, and use the default templates delivered with the plugin.

I tested autocomplete, PHP based search, and instantsearch, without issue in both environments.

From any page in my personal blog, if I enter `algoliasearch` in the browser console, I see it returns the function.
From any page in my personal blog, if I enter `algoliaAutocomplete` in the browser console, I see it returns the function.

![Screen Shot 2021-07-26 at 8 50 51 AM](https://user-images.githubusercontent.com/5407441/127000105-f7b40655-895a-4f8d-a3aa-8bea58622508.png)

On the search results page, if I enter `instantsearch` in the browser console, I see it returns the function.

![Screen Shot 2021-07-26 at 8 49 37 AM](https://user-images.githubusercontent.com/5407441/127000134-cc2a5e02-c884-4d79-8c9e-c3d423654960.png)

@uptimizt so that I understand, you are saying that if you have instantsearch.js enabled, but autocomplete disabled, then you encounter the issue?

@amrutadotorg do you also have instantsearch.js enabled, but autocomplete disabled?

**Comment by uptimizt** [comment]
@richaber 
yes, if I enable a search page with Instantsearch.js and autocomplete, everything is fine.

but, if I disabling autocomplete 
<img width="1389" alt="2021-07-26-17-43-49-50a9r" src="https://user-images.githubusercontent.com/1852897/127008499-c051cf93-8c16-4db1-a92f-4c0903393060.png">

I get the error on the search page and the search page stops working

**Comment by richaber** [comment]
Thank you for verifying that @uptimizt.

I've tagged 2.0.1 here in Github, and am working on pushing it out to WPORG's SVN repo.

**Comment by richaber** [comment]
2.0.1 update has been pushed to WPORG

![Screen Shot 2021-07-26 at 10 33 01 AM](https://user-images.githubusercontent.com/5407441/127016944-8c808344-138d-4f62-9739-bc7046ee150c.png)

![Screen Shot 2021-07-26 at 10 36 35 AM](https://user-images.githubusercontent.com/5407441/127017247-755dcb0f-680f-43ad-aaa3-fbe6e59b3164.png)

Tested on my personal blog, and it appears to resolve the issue if I enable instantsearch and disable autocomplete.
