### ISSUE TITLE
Very slow admin 

### ISSUE THREAD

**Issue by josh-tt** [WebDevStudios/wp-search-with-algolia#180]
**Describe the bug**
Running the plugin locally the admin pages are very slow. 10 sec loads on each click of a page in the admin. All other admin pages are fine, it's only when I click on the plugin admin pages for wp-search-algolia. 

I'm on a fresh install using underscores_tw and using WP LOCAL, nginx, PHP 8.0 and MySQL 8.0.16, WP 5.8.1

**To Reproduce**
1. Go to Algolia admin pages
2. Click on page tabs

**Expected behavior**
Expected that it reacts without so much delay. 

**Desktop (please complete the following information):**
 - macOS m1
 - Safari 
 - 14.1.1

**Comment by richaber** [comment]
I cannot reproduce the issue as described.

![Screen Shot 2021-09-24 at 10 12 26 AM](https://user-images.githubusercontent.com/5407441/134700257-6aae3fd2-ab49-431c-aa69-d5d8af97e417.png)
![Screen Shot 2021-09-24 at 10 12 09 AM](https://user-images.githubusercontent.com/5407441/134700260-e9c32be8-684e-4b9a-97b5-0241df4eed40.png)
![Screen Shot 2021-09-24 at 10 11 49 AM](https://user-images.githubusercontent.com/5407441/134700261-925dc61c-0ad9-4d7a-8499-d87f3519d54e.png)

You may be experiencing slowness due to another package, process, or configuration, specific to your environment.
