### ISSUE TITLE
Woo Taxonomies: Categories & Tags do not populate Categories/ Tags indexes

### ISSUE THREAD

**Issue by seanvandermolen** [WebDevStudios/wp-search-with-algolia#191]
I'm not sure if this is a bug, a feature request or there is a solution I'm missing.

If I look at the product and searchable posts, under taxonomies, product_cat is included.  But that is the extent of it, seems like there would be some kind of correlation with Categories and Tags indexes that would populate the facets on the instantsearch.js page.

Maybe one of these?

algolia_post_shared_attributes | array $shared_attributes, WP_Post $post

algolia_post_{$post_type}_shared_attributes | array $shared_attributes, WP_Post $post

**Comment by tw2113** [comment]
@seanvandermolen I know it's been almost a year, but I'm not quite following on this one.

Is the issue in what's getting into the index in your Algolia dashboard? Or that those aren't getting included for faceting on the front?

**Comment by seanvandermolen** [comment]
Since writing this I've come to understand how this plugin works a bit better.  

What does not make sense to me is the searchable posts index/ All Posts setting under autocomplete.   It's clear that it indexes posts and products taxonomies (lumped together).  Then there is the granular options in autocomplete settings.  I can't remember why I think this, but something I saw a while back trying to learn how things worked lead me to believe that search results and autocomplete use two separate indexs, but I could be wrong.

My question is how to include the taxonomies for product categories and terms to show up as facets to filter results.  Because if I selected them in autocomplete, they show up in their own indexes and they are included in the searchable_posts under taxonomies like so.

`{

product_type:

[ "variable" ]
1 item
product_cat:

[ "New Items", "Giveaways", "Service", "Detailing Products" ]
4 items
pa_allow-gift-message:

[ "Female" ]
1 item
pa_enable-product:

[ "Male" ]
1 item
pa_packages-of:

[ "250 pcs", "500 pcs", "750 pcs", "1000 pcs", "1500 pcs", "2000 pcs", "2500 pcs", "3000 pcs" ]
8 items
pa_quantity:

[ "Male" ]
1 item
pa_tax-class:

[ "Female" ]
1 item
pa_visibility:

[ "Red" ]
1 item
}`

**Comment by tw2113** [comment]
Have you reviewed the Algolia.com dashboard configuration settings at all? Not the worst place to start and also try things out before potentially putting those same setting changes into code and pushing via API/settings buttons in the plugin's settings pages.

**Comment by seanvandermolen** [comment]
Yes, and i do see that if i can created indexes with metadata & terms.  For me the documentation isn't clicking and the settings are confusing.  You have all these available taxonomy terms that you can include in autocomplete/ or choose all posts.  Which I assume includes all posts, but not necessarily CPT's or even products?

Then there is this paragraph in the docs "attributesForFaceting Algolia allows you to prepare your records for faceting. Faceting is the feature that allows you to list all posts of a category. Out of the box usage of faceting is not included in the plugin, however some default values for the attributesForFaceting are included."  What are those?

But then if Faceting on the Search Page is what I'm trying to achieve, what do all these selectable terms in autocomplete have to do with it.  As far as I under stand it, that just let's you granularly decide what is searchable for autocomplete which doesn't really facet anything, but you could include things like blue, large shirt.

If there is an association between the settings on the autocomplete page and what is searched and displayed on an instantseasrch results page... it's really lost on me.  Because when I search tons of attributable products show up that were never selected in the autocomplete page.  Which leads me to believe the search page is indexing everything and using the all posts index.  If those terms on the autocomplete page do effect the search results page, would it not make more sense to give them a general settings page instead of under autocomplete?

Granted, the dataset I'm working with is a bit of a mess.. and I don't spend all my time tinkering with different settings.  But I have spent a descent amount of time with it and easily get lost with what the plugin does and doesn't do, thus requiring customization.  

Last but not least, it the documentation doesn't really cover faceting especially on the search template page, but I guess if I dug back into the Algolia github docs I might learn more... It's just the last time I tried to figure out how to customize the look and layout of the search results I spent days digging through Algolia instant search docs and examples only to find an untouchable template that made all the docs and examples worthless.  I wound up using their ecommerce examples CSS to get the look I wanted but I wasted days on that.

**Comment by seanvandermolen** [comment]
Ugh, so as I was writing this I opened the alogia dashboard just to check what I was thinking made sense and I've been so focused on the results I completely missed the facets sitting right there lol. Well that is a very me thing to do, so now I have some work to do.

The last thought I have, why does the doc say "Out of the box usage of faceting is not included in the plugin"  looks like it grabbed everything.

**Comment by tw2113** [comment]
For what it's worth, the plugin was originally managed by Algolia themselves, and they decided to abandon for whatever reason they had. Perhaps they didn't want to try to be WordPress experts at the level needed. Who knows.

WebDevStudios decided to adopt the plugin and take over all official support and maintenance of it. I bring these parts up to say that I haven't been involved since the start, and can only hunch at times.

Regarding your point of "Out of the box usage of faceting is not included in the plugin", my hunch is that it's a case of the people involved had no great way to predict exactly what attributes would want to be available for faceting by default, especially at a level of everyone installing the plugin. So they took the route of "sane defaults" and make sure that the customization can be done for each site's needs afterwards.

Regarding what the plugin does, in a layman's terms style, I'd say it does a pretty great job of indexing a site's content, provides ability to replace standard WordPress search with search coming from those Algolia indexes, and then also provides autocomplete and instantsearch library access as well as some default templates that make use of those libraries.

Autocomplete, in case not completely aware of how it works, takes over the search input and makes "smart" suggestions based on what's been typed in. If someone finds the match they were hoping for, they can click on that suggestion and go right to it. Or they can click enter and get the overall search results and whittle down from there.

Instantsearch takes over the search results display and has attribute filtering available through various widget types, some of which we ship with the plugin, and many more are available with Algolia's documentation.

Last thing that is capable of being done, but isn't necessarily a requirement, is you can actually manage the settings through code and with the plugin, and any of the configuration settings you see in your Algolia Dashboard should be able to be configured from code. One benefit of this is that you could version control settings and configuration for multiple site environments or for multi-person teams. You wouldn't need to go into multiple search index dashboards and try to remember every single tweak made and remake them by hand, you would have it all in code that you could click one button and push up all of them at once. However, like mentioned earlier, this isn't a requirement.

**Comment by seanvandermolen** [comment]
I like what I've got out of it so far.  Just need to spend the time to learn all the ins and outs.  Thanks for supporting the plugin and providing background.  It really is a great solution compared to most everything else.

**Comment by tw2113** [comment]
I know I took to Algolia a lot easier than I did ElasticSearch :D

**Comment by tw2113** [comment]
Closing as a non-issue at the present moment.
