### ISSUE TITLE
Update PHP API Client

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wp-search-with-algolia#20]
Need to get the latest PHP API Client running in the backend. 

https://www.algolia.com/doc/api-client/getting-started/install/php/?language=php

**Comment by gregrickaby** [comment]
Quick update for @richaber 

I created a branch and used WP-CLI to scaffold a plugin. I'd love it if you could take the PHP side of things, and go all "Senior BEE" on it.

https://github.com/WebDevStudios/wp-search-with-algolia/tree/feature/refactor-from-scratch

**Comment by richaber** [comment]
Branched off to https://github.com/WebDevStudios/wp-search-with-algolia/tree/feature/refactor-from-scratch-php temporarily for PHP refactoring.

**Comment by richaber** [comment]
I don't think either `typisttech/imposter-plugin` or `coenjacobs/mozart` will work for this. 

Unfortunately, the newer Algolia Client appears to be too complex for `typisttech/imposter-plugin` to prefix in a usable manner.

`coenjacobs/mozart` appeared to handle it better by moving Algolia out of `/vendors/` and into `/src/Vendors/` with our prefix.

However, in the course of testing, I happened to have Guzzle present on my install. The newer Algolia Client tries to automagically use `Guzzle` (without me explicitly asking for it), which triggered fatal errors, due to PSR interface mismatches related to prefixing.

At this point, I think we remove the prefixing (`typisttech/imposter-plugin` / `coenjacobs/mozart`), and _do not_ autoload Algolia Client.

The older 1.x version, which was a fork of Algolia's own WP plugin, used the (admittedly somewhat gross) [classmap.php file](https://github.com/WebDevStudios/wp-search-with-algolia/blob/1.1.0/classmap.php) to load the client. It also provided the [`algolia_should_require_search_client` filter](https://github.com/WebDevStudios/wp-search-with-algolia/blob/1.1.0/classmap.php#L8) so a dev could disable loading the Algolia Client that came with the plugin, if they had their own compatible version to load. I may revisit that concept.

**Comment by richaber** [comment]
It would appear that both Delicious Brains and Yoast use humbug/php-scoper to accomplish the namespace prefixing:
https://deliciousbrains.com/php-scoper-namespace-composer-depencies/
https://developer.yoast.com/safely-using-php-dependencies-in-the-wordpress-ecosystem/

**Comment by drzraf** [comment]
Did this go somewhere?
For the JS side, it's easy to not rely on the plugins with ~150 lines of `search.php`, `search.js` [basically similar to this](https://github.com/WebDevStudios/wp-search-with-algolia/blob/feature/refactor-from-scratch/src/index.js) + some mustache.

But the indexation side is trickier and that's where this PHP-refactor part would be helpful.
I suggest to simply go with `composer` + `require autoload.php` (if not using Bedrock).

**Comment by richaber** [comment]
Howdy @drzraf 

> Did this go somewhere?

This is work in progress for WP Search with Algolia version 2.0.0.

> But the indexation side is trickier and that's where this PHP-refactor part would be helpful.
> I suggest to simply go with `composer` + `require autoload.php` (if not using Bedrock).

No, we are not using Bedrock.
The PHP refactoring branch does use composer.

**Comment by richaber** [comment]
Just noting that we did actually update the Algolia Search API Client for PHP to version [2.7.0](https://github.com/algolia/algoliasearch-client-php/releases/tag/2.7.0) when we released WP Search with Algolia version [1.4.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/1.4.0), as it entailed minimal risk.

**Comment by richaber** [comment]
Closing as [WPSWA 2.0.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0) includes [Algolia PHP API Client v 3.0.2](https://github.com/algolia/algoliasearch-client-php/releases/tag/3.0.2)
