### ISSUE TITLE
Change name of default index

### ISSUE THREAD

**Issue by GioAceto** [WebDevStudios/wp-search-with-algolia#205]
The default index created is called "wp_searchable_posts". Is there a way to change the actual index name and not just the prefix? I plan on having multiple indexes for multiple sites using this plugin. 

The issue I am having is that I am trying to use the WP CLI to reindex just **this** index (not all) but you can't include prefixes in the command (it errors out) and I can't change the index name for the plugin. It only lets me index on "wp_searchable_posts" but I can't have every site using "wp_searchable_posts" as the index name. I need different ones for each site.

`wp algolia reindex searchable_posts`

Changing the index name in the Algolia dashboard won't work because it always ends up creating a new index called "wp_searchable_posts" if it doesn't exist, the next time I reindex.

**Comment by tw2113** [comment]
I believe the `searchable_posts` part comes from Algolia themselves. I do know we have this tip/trick over at https://webdevstudios.com/2021/02/09/wp-search-with-algolia/#index-prefix-for-multiple-environments that discusses prefixing for multiple environments.

That said, I just ran the following and it indicated that it only did so for my specific prefixed index, instead of ALL of them and I know that the dashboard this test site is tied in to has multiple sites pushing to it:

```
$ wp algolia re-index searchable_posts
Processing 22 pages of results.  100% [====================================================================] 1:03 / 0:23
Success: Indexed "22" pages of results inside index "mdb_wp_searchable_posts"
```

The set prefix for my install is `mdb_wp_`.

So I think you may be good and covered already? Perhaps try it out from different installs and see if the same behavior lines up, as a test.

**Comment by GioAceto** [comment]
Thanks Michael, it works in the command line, but I really need this to run in the code instead. I've tried both of these commands but it doesn't seem to work:

`WP_CLI::runcommand('algolia reindex searchable_posts');`
`WP_CLI::runcommand('algolia reindex');`

I was thinking that this should be doing the exact same thing as me writing it in the command line. Does WP_CLI need to be initialized somewhere before I can run WP_CLI commands in the code?

I have a WP cron job that runs a function, and I need to reindex every time it runs. This seemed like the easiest way if it could just run the WP_CLI command in the php. We definitely don't want to have to press the reindex button manually every day in Wordpress.

Your help is much appreciated!

**Comment by tw2113** [comment]
Hmm...it's been some months but I recall someone else wanting to somehow programmatically trigger indexing, and at least from what I'm remembering, we had no great answer in terms of a code version of this. I think we recommended not using WP Cron and instead a "real" cronjob that could run a bash command like we have with `wp algolia re-index searchable_posts`. Beyond that, it was always via the buttons in the UI, which I definitely get wanting to not have to do.

**Comment by GioAceto** [comment]
I was able to reindex programmatically with the `shell_exec()` command within the code.

**Comment by tw2113** [comment]
Whatever gets the job done, right?
