### ISSUE TITLE
Add filters to allow for "merging" taxonomies into less indexes

### ISSUE THREAD

**Issue by moory-se** [WebDevStudios/wp-search-with-algolia#215]
We have ~250 Woocommerce attributes that we want to be searchable. These could things like

- Color
- Brand
- Season
- Gender

With the current setup, each attribute is creating it's own index. While this is good in many cases (it allows different settings per index etc), it does make each keystroke ~250x more expensive since Algolia charge per index.

It would be very benificial if we could merge multiple attributes/taxonomies into 1 index. This would need a filter in `Algolia_Index::get_name()`. I do understand that this would make the Admin page of Autocomplete "broken", and that other filters (`algolia_term_{$taxonomy}_record`) would be broken. 

It leaves us with creating something more sophisticated. I think the simplest way would be to create one (1) special index which is a "merged terms index". Each individual taxonomy can be (with a checkbox) added to that index. It would run it's own filter (`algolia_term_merged_terms_record` etc). 

If you think this would fit your plugin, I could take a stab at it and make a PR. I fully understand that you can't accept the PR you haven't seen, but if you simply think this functionality shouldn't be offered by the plugin it is a waste of time for me to try to implement it. If that's the case - I would be super happy with the above mentioned filter in get_name() to solve my needs :)

**Comment by tw2113** [comment]
The fact that, depending on how implemented, it'd break expected available behavior has me feeling rather hesitant to merge everything into the plugin directly and pushed out to all our users.

On the topic of merged/combined indexes, we need to keep the size in mind, as per the following links:
https://support.algolia.com/hc/en-us/articles/4406981897617-Is-there-a-size-limit-for-my-index-records-/
https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/

This one may help in terms of modifying how things are fetched, without attempting to merge content into fewer indexes:
https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/

I feel confident enough to say that while we can't merge everything into the core plugin, we absolutely would love to see people extending the plugin with their own offerings that people could make use of in their specific use cases.

Can you point out which file and area in that file that you're needing that `get_name()` method/filter to be in?

**Comment by tw2113** [comment]
I believe it's https://academy.algolia.com/training/3a0e7ce4-7782-11ec-91df-02aea812ea2d/overview where they talk about optimizing relevance and how too many searchable things can actually be detrimental than too few. 250 searchable attributes, I must believe would really fall into the too much from Algolia's perspective.

I am going to close this issue for now, but if someone comes by and provides extra confirmation that it should actually be done somehow, we can revisit at that time.

**Comment by moory-se** [comment]
Hi,

I think you misunderstand me. It's not "250 searchable attributes" - it's rather "250 different pages to be found". Examples:

- Color: red (site.com/color/red)
- Color: blue (site.com/color/blue)
- Brand: nike (site.com/brand/nike)
- Brand: adidas (site.com/brand/adidas)

On many other platforms, these "pages" are in the same table ("algolia index"). In woocommerce they're not. To merge them all (with 3 attributes: id, name ("nike"), url ("site.com/brand/nike") would allow a real full site search while not at all conflict with the optimizing relevance guide you linked to.

**Comment by tw2113** [comment]
Are you creating these indexes via the Autocomplete settings page? That's the only place I can think of where WooCommerce attributes would potentially get their own index. Otherwise, they'd just be attributes on the product objects themselves that are a would be a part of the "product" index and could be marked as searchable that way.

**Comment by moory-se** [comment]
I really fail to communicate, sorry for that. 

Yes - they are created through the Autocomplete settings page. There's a huge difference between having them as "searchable on a product" and a dedicated index: the former would show the product and the latter would show an archive page with all the products on it.

Everyone expects Brands to be searchable as its own entities. I strongly feel that having one (1) index where you can add many different taxonomies is the standard solution in e-commerce. This is not far from the "searchable_posts" that's shipped with this plugin (that is, p"osts of different post types" instead of "terms of different taxonomies").

**Comment by tw2113** [comment]
I'm hearing you, but at the same time I'm wondering if we're not quite thinking on the same page still.

The autocomplete settings page and associated line items in that table add in sections to the autocomplete dropdown. As an example with one of my own sites:

https://cloudup.com/cN6XuZzaJlC

I have the following content types checked in my autocomplete settings page: books, posts, pages, bookmarks, music videos

While yes these aren't taxonomy terms, each gets its own section in the dropdown shown in the screenshot.

You bring up the idea of an archive, which has me thinking of a URL like https://www.myshop.com/product-category/brand/nike or https://www.myshop.com/brand/nike to show Nike products and then the ability to just search through those and limit it to just Nike products.

Is that what you're trying to get to ultimately, perhaps also with say an archive like https://www.myshop.com/product-category/brand/ where you can search brands before landing on a product archive for just that brand?

Trying to make sure we're on the same page with your ultimate goals, because if I'm closer than I was with my comments about the archives, then that's a different thing than indexes that the Autocomplete page sets up.
