### ISSUE TITLE
Question: Does this plugin work with WP multisite?

### ISSUE THREAD

**Issue by bwaltz** [WebDevStudios/wp-search-with-algolia#217]
We evaluating the pros and cons of using a multisite setup for an upcoming project and since we've used this plugin on a few single sites we just want to make sure it will still work.

Thanks!

**Comment by tw2113** [comment]
I am personally not sure how compatible the plugin is with Multisite and the biggest questions is how the indexes behave. For example if they can all go into the same index, should they? can/should each site get its own index prefix to help with per-site indexes.

I'm suspecting that prefixes can be set per-site in the install, but I would need to confirm first.

**Comment by bwaltz** [comment]
Thank you and thanks for the plugin! Anything you uncover would be great to know when making our decision.

**Comment by tw2113** [comment]
Alright, i'm not seeing any issues with multisite as a whole. You ARE going to want to set a unique prefix for each site in your network that will be using Algolia. Leaving the prefix the same for each was overwriting indexed items, as post IDs are used as the unique values.

Template overrides with changes made in your active theme should be just fine. Each theme should get its own copy of the template file being customized. If by chance you're using the same theme in all the sites in the network, then you'll need to include your own conditional checks if each site needs different changes.

Otherwise, I think you should be just fine with this.

**Comment by tw2113** [comment]
Closing the issue as it's more just questions, but we can continue the discussion after that.

**Comment by bwaltz** [comment]
Super helpful! Thank you!
