### ISSUE TITLE
Search Result Template Customization

### ISSUE THREAD

**Issue by kamal87g** [WebDevStudios/wp-search-with-algolia#222]
Hi Team,
I want to get search result template as like https://simplifaster.com/search/
I make plugin template folder in my current theme and renamed it like  /my-current-theme/wp-search-with-algolia/
but not reflect my changes. can you please suggest a solution for inherit template in my theme.

Also can you let me know I can add product price in custom field support using these hooks. look like it does not fetch product ids from post.
add_filter( 'algolia_post_shared_attributes', 'wds_algolia_custom_fields', 10, 2 );
add_filter( 'algolia_searchable_post_shared_attributes', 'wds_algolia_custom_fields', 10, 2 );

![image](https://user-images.githubusercontent.com/16898100/174879636-3dace92d-04d4-4d32-9770-3d2e8b4efc3b.png)

**Comment by tw2113** [comment]
I would review the wiki for this topic, especially https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Customize-Templates#default-location-of-template-files for this initial part.

You have the folder name wrong for your copy in the theme, it should be in a folder just named "algolia" for example.

Those filters are meant to be used to include the specified data at the time of post indexing. For example, with our blog post from last year https://webdevstudios.com/2021/02/09/wp-search-with-algolia/

The example custom field functions/callbacks are fetching the meta data before pushing the data up to Algolia, so that that information is included in the index for that post object. You'd want to get your information included at that point, and then when it comes time to rendering a given post object as part of the results, you'd have that information hopefully available to render (assuming that it got pushed up initially). For example with https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/templates/instantsearch.php#L47-L69 which is what renders each "hit" result. If you pushed up an attribute of "my_price", then you should be able to access it in the template display with `{{ data.my_price }}`
