### ISSUE TITLE
¿Work this plugin with woocommerce?

### ISSUE THREAD

**Issue by mrenzo20** [WebDevStudios/wp-search-with-algolia#293]
¿Is this plugin compatible with woocommerce?
¿From indexing to searching on frontend?
Thank you.

**Comment by tw2113** [comment]
Hi @mrenzo20 

Since products are registered as searchable, they already get indexed automatically with the "Search page" settings when used for either "Backend only" aka WP_Query integration, but also for when using "Instantsearch".

When on the autocomplete settings page, they're available as one of the options to index for Autocomplete integration as well.

The differences are that both use what I'll call the "standard content details" to be indexed and very similar to what would be included for posts and pages, nothing necessarily specific to WooCommerce products like SKUs, prices, etc out of box.

That said, I did write up a 3-part blog series on the WebDevStudios.com blog that talked about more details specific to WooCommerce and getting those types of things added and configured. 

There will be details about settings configurations, template customizations, and also Algolia widget work to help shape an overall better WooCommerce experience.

You can see those at the following links:

https://webdevstudios.com/2022/09/13/wp-search-with-algolia-settings-configurations-woocommerce/
https://webdevstudios.com/2022/10/11/wp-search-with-algolia-autocomplete-instantsearch-customization/
https://webdevstudios.com/2022/11/03/integrating-wp-search-with-algolia-instantsearch-widget/

Hope that helps add some clarifications and gives some ideas of what can be done. Closing the issue as not an enhancement or a bug, but we can still comment back and forth as needed for the moment.

**Comment by mrenzo20** [comment]
A lot of thanks! I will read this and try it.
