### ISSUE TITLE
Review and consider revising author/user attributes that get indexed.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#326]
As is, we index the following, and it is part of the original fork we made from Algolia's plugin.

```
$author = get_userdata( $post->post_author );
if ( $author ) {
	$shared_attributes['post_author'] = array(
		'user_id'      => (int) $post->post_author,
		'display_name' => $author->display_name,
		'user_url'     => $author->user_url,
		'user_login'   => $author->user_login,
	);
}
```

There is user concern at the forum link at the end of this issue about exposing too much. Most particularly in my mind, author ID. Display name, URL, and login are mostly useful, with the login being "iffy" since it would be part of the URL as well. The URL is the author archive which is often meant to be public.

Do we want to perhaps remove the numeral ID as part of the indexing? Note this would be a potential breaking change for users.

https://wordpress.org/support/topic/usernames-in-index-data/

**Comment by asharirfan** [comment]
@tw2113 I have taken a good look at the code of the plugin, the user index in Algolia and the user table in a WP site's database.

The only place, where I can find the `user_login` field being indexed, is as the details of the post author in the _Posts_ and _Searchable Posts_ indices. I am not sure how to deprecate the field yet because if we remove it, this has the potential of breaking websites.

Following is the data being indexed in the Users' index:

![image](https://github.com/WebDevStudios/wp-search-with-algolia/assets/8023941/ababb338-6497-4458-a4c6-c7b9a4c2d6dd)

I think we can also think about deprecating `user_id` attribute from the index. But then again, this has the potential of breaking end-user websites. I think we should include this update in the next major update.

But I think that's about it. I don't think there is another attribute for a user that can be considered sensitive.

**Comment by tw2113** [comment]
@asharirfan for what it's worth, as I recall, the original issue was with regards to what gets indexed as part of the post information, so the `post_posts` autocomplete indexes and the `searchable_posts` instantsearch indexes would be the primary focus here originally.

In regards to user indexing, thankfully we do not enable that by default, and only have it available for autocomplete as well, so less to worry about, but honestly not sure how many people may indeed be using it too. This one feels potentially niche, but still absolutely potentially used.

Ways forward? We would need to communicate well for sure.

Perhaps in a minor release, we could add some sort of "is_new_install" flag that could be used to conditionally set the attributes to be indexed. If a new install, then they get whatever reduced amount we choose. If it's an upgrade, then it gets all the defaults that we've had for a long time.

Alternatively, we could provide a quick snippet for upgrading folks, if we decide to remove some for everyone, to regain the same attributes, and I just take on the support requests regarding it. Probably not the best idea here, but it's an idea.
