### ISSUE TITLE
On single product update image is removed 

### ISSUE THREAD

**Issue by atindersingh67** [WebDevStudios/wp-search-with-algolia#381]
**Describe the bug**
I am using this plugin and facing one issue. If  i do re index all content i can see the image urls in my algolia index. But on update of a single product it removes the image url from my algolia index for that product. 
I am using external image plugin for the images 

**To Reproduce**
1.Install External Image Plugin 
2. Create a product and add image as a url.
3. Save product and re index all content.
4. now edit the same product and just click on update button. the image will be removed from algolia index.

**Expected behavior**
On edit product it should update or persist the image in the algolia index.

**Comment by tw2113** [comment]
Hi @atindersingh67 

Since this sounds very familiar, do you have an open issue on our support forums already? I know we have at least 1 forum thread about external images.

Because of that, my question still stands about order of operation and if the meta data is saved to the post already at the time of indexing, or if this external image data is being pulled in afterwards. We can't control via our plugin, what information is available at the time of indexing, thus we push what is available.

**Comment by tw2113** [comment]
What plugin are you using for the external image aspect?

To be certain, have you checked the meta data inside the WP install to confirm, I assume, the URL is in fact saved as part of the object data?

**Comment by tw2113** [comment]
hmm. I'm not going to have access to that plugin, so it's hard for me to do any testing on my own.

I would assume as long as the image URL is on the algolia object/hit, it would be able to be used. Much like the `permalink` property is.

The only other idea I have would be somehow checking the state of the records at this point in the code: https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/indices/class-algolia-index.php#L379-L383

This would need to be done with something like XDebug or similar so that you can inspect everything right before the push to Algolia, to see/confirm what data is going to be put into the record.

**Comment by tw2113** [comment]
Hi again @atindersingh67 

Question for you, does the external image url and whatnot get stored as custom field data? If yes, I have some code for you to test some functionality with.

**Comment by tw2113** [comment]
@atindersingh67 Any news or changes here? We have what we feel may be a solid lead with some things that could help with this.

**Comment by tw2113** [comment]
I have been informed that Algolia has been moved away from by the original reporter, so closing this as a non-issue at the moment.
