### ISSUE TITLE
Need to list down all other indexNames which are not from WP

### ISSUE THREAD

**Issue by timir999** [WebDevStudios/wp-search-with-algolia#49]
Hello Guys,

First of all thanks for taking initiative to give support and enhancements for this algolia plugin. 
Now I am facing one issue here. We have an algolia account and it have indexes from wordpress and Magento as our store is managed by Magento 2 and CMS is managed by WP. 
When I see in settings of this plugin, it shows only those indexes of post types which are part of WP. So how can I include my other indexes for search? 
I hope you understand my issue. Can you please guide me on this?

Thanks
Timir

**Comment by richaber** [comment]
Howdy @timir999, 

Out-of-the-box, this plugin does not integrate with additional indexes, and only searches those managed by the plugin itself (which only really relates to what's in the WordPress database).

That being said, if you're using the JavaScript powered search components, you can copy the autocomplete.php and instantsearch.php templates out of the plugin and into your theme, so that you can customize the way the JavaScript powered search works. 

I found an [older reference here](https://discourse.algolia.com/t/using-multiple-indices-on-wordpress/2617/2) that might get you started with ideas on how you might accomplish such a customization.
