### ISSUE TITLE
Default post type filter on search queries

### ISSUE THREAD

**Issue by mladen16** [WebDevStudios/wp-search-with-algolia#51]
Hello Guys,

Could you please allow us to have more control of post type on search pages by adding the filter here https://github.com/WebDevStudios/wp-search-with-algolia/blob/master/includes/class-algolia-search.php#L125

This is fixing the issue for us:
`$post_types = ! empty( $query->get( 'post_type' ) ) ? $query->get( 'post_type' ) : 'any';`
so something like:
`$post_types = apply_filters( 'algolia_search_default_post_type', 'any', $query );`
would be really helpful.

Thank you!

**Comment by richaber** [comment]
Howdy @mladen16,

Could you provide more details about your use case?

**Comment by mladen16** [comment]
Hello @richaber,

Thanks for your reply.

Well, we are using 4 different search forms with algolia instant search dropdown integrated and we are overriding default autocomplete files in our theme so that we can use different post types on different search forms ( we even joined two post types in one search form ).

We want to have the same result on search pages so we enabled "Use Algolia in the backend" option in Algolia Search -> Search Pages.

The problem is that we have some custom filtering functionality on some search pages where we are changing post type by modifying query using 'pre_get_posts` filter and we don't have `post_type` query arg set in search form or URL.

Also, there is a conflict with one third party plugin which is not using `post_type` query arg, but have custom parameter instead.

Adding the filter I mentioned is fixing our issues. Also, if I may add, maybe there should be the filter for posts per page param.

Hope I was clear enough, but I am not sure about it :)

Thank you

**Comment by richaber** [comment]
Since we hook into pre_get_posts at priority 10, you should be able to hook in at a later priority (11, or later) and modify the post_type argument without the need for an additional filter, if I'm understanding correctly.

As for `posts_per_page`, have a look at line 122 of [includes/class-algolia-search.php](https://github.com/WebDevStudios/wp-search-with-algolia/blob/7a025831b3835e20d4bb729ed33b685058f905c0/includes/class-algolia-search.php#L122). Note that we use the value of `$params['hitsPerPage']` for the `posts_per_page` parameter. `hitsPerPage` is filterable at [line 76](https://github.com/WebDevStudios/wp-search-with-algolia/blob/7a025831b3835e20d4bb729ed33b685058f905c0/includes/class-algolia-search.php#L59-L85). Since that is a "pagination" related param, both for the Algolia index and the WP Query, try filtering `hitsPerPage` instead, which should then carry through to `posts_per_page`.

**Comment by mladen16** [comment]
Hi @richaber,

Ok, sure, just thought it could make our lives easier.  :) Not really sure what is the purpose of overriding `post_type` at all, though. Thanks for your time and for taking over the plugin.
