### ISSUE TITLE
Search Multiple indices for instantsearch.js

### ISSUE THREAD

**Issue by witu9217** [WebDevStudios/wp-search-with-algolia#52]
Is it possible to implement the search for multiple indices through instantsearch.js. I can see that it works for autocomplete.js but not for instantsearch.js?

**Comment by richaber** [comment]
Howdy @witu9217 

Out of the box, our bundled _implementation_ of instantsearch.js only searches the searchable_posts index (`algolia.indices.searchable_posts.name`) so that it "just works" for most users.

For developers, they can copy the `wp-search-with-algolia/templates/instantsearch.php` template file from the plugin into their theme for customization.

It _should_ be possible to search multiple indices with instantsearch.js, but I'm not able to provide a quick solution. I can say that you would _probably_ need multiple instances of `instantsearch` (one for each index). You should be able to tie the instances to a single searchBox input using the [`searchFunction`](https://github.com/algolia/instantsearch.js/blob/v1.11.15/docs/_includes/widget-jsdoc/instantsearch.md) option.

Beyond that, I'm not sure I can provide much more direction.
