### ISSUE TITLE
Support for 3rd party plug-ins (WPML, ACF, Elementor)

### ISSUE THREAD

**Issue by lazmo88** [WebDevStudios/wp-search-with-algolia#58]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem. 

**Describe the solution you'd like**
I think many people would enjoy improved UX if most popular 3rd party plug-in support would be available to be enabled on this plugin. Plug-ins such as WPML, ACF and Elementor support would be popular options.

WPML example: https://community.algolia.com/wordpress/wpml.html

By default posts from all languages are indexed and returned in search. Therefore additional data is required to filter per language and return more relevant results. 

ACF example: https://community.algolia.com/wordpress/advanced-custom-fields.html

ACF support would require simple GUI to enable additional fields to be indexed into Algolia. This could be achieved by fetching Post Types, Custom Post Types and their custom fields. Once fetched, simple checkbox next to items would enable/disable indexing to Algolia. 

Elementor, no example, but it would be great to have a GUI to build custom InstantSearch.js templates with custom Elementor blocks. As Elementor allows creating custom blocks, it would be viable to build different InstantSearch widgets and use power of Elementor to customize search experience. 

**Describe alternatives you've considered**
Only way is to manually edit plugin or WP files, which is not optimal for all users. 

**Additional context**
This feature request is to open discussion focused on improving UX by enabling support for 3rd party plug-ins.

**Comment by richaber** [comment]
Howdy @lazmo88.

WPML and ACF are _indirectly_ supported, in the sense that you can customize indexing of fields through filters, and customize the search experience through your own custom autocomplete/instantsearch implementation. I know virtually nothing about Elementor, other than it's a page builder plugin.

I am certainly open to discussions about improvements for this plugin. However, I would be hesitant to declare any _official_ support, or integration, with third-party plugins for many reasons. Especially commercial plugins that require paid licensing.

The level of effort to build, maintain, and support said integrations, especially for more complex plugins, would likely be prohibitive. There are a lot of competing commercial plugins out there, and I wouldn't want to appear to favor one over another. And there are other areas of the existing codebase that require more urgent attention, such as upgrading the bundled libraries, documenting the existing code and hooks, and improving tooling.

I am certainly open to doing a little more work around translations, _but_ there are so many translation plugins that do things _their own way_. According to the [WordPress Roadmap](https://wordpress.org/about/roadmap/) "(Gutenberg) Phase 4 will contain support for multilingual sites." Presumably, there will be some sort of coalescing around how best to handle translations of _content_ at that time. I would prefer to be a little more agnostic about where I apply translation efforts, rather than adding explicit support for a specific plugin, I would want to apply that effort in a way that would have a broader impact for the whole user base. For example, making it easier to translate "literal strings" (not _content_) for the client side JS is one area that could be a "win," based on fairly recent translation related questions.

The post type labels shown in autocomplete, could potentially rely on the current locale ([reference](https://wordpress.org/support/topic/wpml-post_type_label-for-different-languages/#post-12312956)). It might be possible to do similar with the `results found in [..]ms` text in instantsearch ([reference](https://github.com/WebDevStudios/wp-search-with-algolia/issues/35)).

If, however, one or more commercial plugins wanted to provide their own integrations with this plugin, or if a third-party developer came along and wanted to create an "add-on" plugin to provide integrations, that would be pretty cool. If there are additional hooks or data that we could expose to help facilitate that, I would certainly be open to doing so.
