### ISSUE TITLE
Adding file to using Repeater in Flexible Content with ACF does not get indexed

### ISSUE THREAD

**Issue by jacobwise** [WebDevStudios/wp-search-with-algolia#77]
**Describe the bug**
When a file is added to a page using an ACF field, it is not indexed in the posts_attachment index. My use case was a file in a repeater in a flexible content section.

**To Reproduce**
1. Add flexible content section to page that is a repeater which has a file upload in it.
2. Upload file. 
3. Check media library that the file was uploaded and attached to the page.
4. Check Algolia index and media attachment is not there.

**Expected behavior**
I expect the media item to be indexed in the posts_attachment index

**Screenshots**
![Screen Shot 2020-07-20 at 12 50 39 PM](https://user-images.githubusercontent.com/2576857/87964320-09fa8f00-ca88-11ea-8a76-f08c37374749.png)
![Screen Shot 2020-07-20 at 12 50 52 PM](https://user-images.githubusercontent.com/2576857/87964325-0cf57f80-ca88-11ea-888e-08c4a549fade.png)
![Screen Shot 2020-07-20 at 12 51 34 PM](https://user-images.githubusercontent.com/2576857/87964332-0ebf4300-ca88-11ea-8169-c87445eb332b.png)

**Desktop (please complete the following information):**
 - OS: macOS (Mojave)
 - Browser Chrome
 - Version 84

**Comment by richaber** [comment]
Howdy @jacobwise.

It sounds like you expect a media attachment post, created when an attachment is uploaded via an ACF field, to be available in the "post_attachments" index.

Assuming the "Media" (post_attachments) index is enabled, the attachment post should be indexed when the corresponding attachment post object is created. That is, if ACF uses WordPress Core functionality to insert the attachment post object.

Attachments should be synced on the `add_attachment` and `attachment_updated` hooks (ref: [Algolia_Post_Changes_Watcher::watch()](https://github.com/WebDevStudios/wp-search-with-algolia/blob/78933d587d9e5edbea92cc7f65a77a1f0adb4326/includes/watchers/class-algolia-post-changes-watcher.php#L38-L40)).

I'd be curious to know if the appropriate hooks fire when ACF handles a media upload, in a repeater field, as described above. I can perform a little testing to see if the hooks fire and the attachment is synced, as I do not know right off hand if attachments uploaded by ACF trigger the appropriate hooks.

**Comment by richaber** [comment]
Howdy @jacobwise,

This appears to be related to the `Algolia_Posts_Index::should_index_post()` [method](https://github.com/WebDevStudios/wp-search-with-algolia/blob/dcb43d51ee5071945db19f2530b5d00103a3b625/includes/indices/class-algolia-posts-index.php#L54-L61 
).

In my testing, I created a new post but did not publish it. I uploaded a PDF with ACF's "File" field. A media attachment post was created for the uploaded file. The media attachment post had a `post_status` of `inherit`.

The `should_index_post` method saw the attachment post had a `post_status` of `inherit`, which then triggered checking the `post_status` of the _parent_ post (which in this case is the unpublished/draft post), and did not index the attachment post.

After publishing the test post, I uploaded a second PDF file through the very same ACF "file" field. That media attachment post object also had a `post_status` of `inherit`, which also triggered checking the `post_status` of the _parent_ post (which in this case was now set to publish) and the attachment post was indexed.

Reading the code, it appears this may have been intentional behavior, to prevent indexing of attachments to unpublished and/or password protected content.

That behavior can be overridden with a little custom code hooked to the `algolia_should_index_post` filter. Something like this should work:

```
/**
 * Index media attachment posts, even if the parent post is not published.
 *
 * @param bool    $should_index Whether the post should be indexed or not.
 * @param WP_Post $post         The post object to potentially index.
 */
function myprefix_algolia_should_index_attachment( $should_index, $post ) {
	// Let the normal behavior continue.
	if ( 'attachment' !== $post->post_type ) {
		return $should_index;
	}

	// We don't care if the attachment post's post_parent is not published.
	return true;
}

add_filter( 'algolia_should_index_post', 'myprefix_algolia_should_index_attachment', 10, 2 );
```

Alternatively, after a post is published, run the "Re-index" action by clicking the "Re-index" button on the "Media" index, under WP-Admin → Algolia Search → Autocomplete.

Since this appears to be functioning as expected (again, based on my reading of the code), and you have the ability to override that behavior through a hook, and can re-index later, after content is published, I think I will mark this resolved for now. Feel free to reopen, if the above suggestion does not work for you.
