### ISSUE TITLE
Potential Bug In Local By Flywheel Lightning on Windows

### ISSUE THREAD

**Issue by richaber** [WebDevStudios/wp-search-with-algolia#87]
**Describe the bug**

WordPress Support Thread: https://wordpress.org/support/topic/impossible-to-connect-please-check-your-algolia-application-id/

It appears that WP Search with Algolia version 1.4.0, running on Local By Flywheel Lightning, in a Windows Host machine, has difficulty connecting to Algolia's servers, and displays the following message on the settings screen...

> Impossible to connect, please check your Algolia Application Id.

**Screenshots**

![image__1_](https://user-images.githubusercontent.com/5407441/90941423-b60cfe00-e3d7-11ea-9173-c83600cc8370.png)

**Additional context**

Downgrading WP Search with Algolia to version 1.3.0, appears to work for the two Windows/Local Lightning users that have tested that so far.

I do not have Windows to test with, and am relying on user reports (2 that I am aware of) to help diagnose/debug.

I am considering writing a new CLI command for testing issues such as this. I have done some legwork in another branch that may prove useful for that.

I have seen reports of Algolia PHP Search Client and Laravel Scout (which uses the Algolia PHP Search Client) users overcoming an issue that sounds identical by installing a certificate on their server and updating their php.ini to include it. This is the least noisy and most concise explanation that I have seen for that: https://onlaravel.com/83-quickfix-for-impossible-to-connect-please-check-your-algolia-application-id

I have not been able to confirm if installing the certificate in Local Lightning and updating the php.ini solves the issue, and I do not fully understand how Local Lightning works on Windows, so providing support for that may be difficult.

It appears that the Algolia PHP Search Client removed `resources/ca-bundle.crt` in version [2.0.0](https://github.com/algolia/algoliasearch-client-php/compare/1.28.1...2.0.0), and my primary hypothesis at the moment is that the removal of the cert file from the Client may be causing Client cURL requests to fail SSL verification.

![Screen Shot 2020-08-21 at 6 04 02 PM](https://user-images.githubusercontent.com/5407441/90941841-e3a67700-e3d8-11ea-8ab1-38d73ba21428.png)

This might end up being a server configuration issue, if we can't identify some other obvious code issue. Downgrading the Algolia PHP Search Client within the plugin does not seem like a good idea, since we would lose any bugfixes and improvements.

**Comment by richaber** [comment]
This is looking more and more like a server configuration issue
https://localwp.com/community/t/problem-with-cert/19625

> I am trying integrate with Algolia. But i think i have a certificate problem. Because here is [same](https://discourse.algolia.com/t/wordpress-impossible-to-connect-please-check-your-algolia-application-id/9869) 1 problem.
>
> I downloaded latest certificate from https://curl.haxx.se/ca/cacert.pem and added this line to site/conf/php php.ini.hbs
> 
> curl.cainfo="C:\Users\dev\Documents\Sites\site\conf\php\cacert.pem"
>
> Restarted local. It shows in php.ini
>
> But not working. Still getting cert error. I am using Windows 10 and Local 5.4.1+3311

**Comment by dingman** [comment]
@richaber thanks for looking deeper. Still strange to me though, version 1.3.0 of this plugin works fine, but 1.4.0 breaks. Could there be some resiliency added in 1.4.0 to account for this difference?

**Comment by richaber** [comment]
@dingman 

The biggest difference between version 1.3.0 and 1.4.0 of the plugin, is that we upgraded the bundled official [Algolia PHP API Client](https://github.com/algolia/algoliasearch-client-php) from [1.23.0](https://github.com/algolia/algoliasearch-client-php/releases/tag/1.23.0) to [2.7.0](https://github.com/algolia/algoliasearch-client-php/releases/tag/2.7.0).

From what I have read in the code, other than API changes, and some method replacements, the biggest difference that could have an impact on this particular issue, that I can determine, is that they removed their own certificate bundle from the client.

I _think_ we might be able get around that by implementing our own cURL options, but I need to test that.

**Comment by richaber** [comment]
@dingman are you able to modify the php.ini in your local environment?

**Comment by dingman** [comment]
@richaber yes

**Comment by daveromsey** [comment]
Hello @dingman,

I've been troubleshooting this with @richaber and we have a workaround for now. We've discovered that the issue seems to be something specific to Local Lightning on Windows, and that the plugin does work under Xampp. If we use the certificate provided with Xampp in a Local site's setup, then we can successfully connect to Algolia's server using v1.4 of the plugin.

Here's a copy of the certificate provided with xampp: [curl-ca-bundle.zip](https://github.com/WebDevStudios/wp-search-with-algolia/files/5143465/curl-ca-bundle.zip)

Just for the record the xampp version I used is 7.4.1 and it's available here, if you'd like to get it directly from Xampp's maintainers: https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.4.1/

I edited my Local site's `D:\dev\local-sites\wp-algolia\conf\php\php.ini.hbs` file and pointed it to my Xampp install's certificate file under a the `[curl]` section, which I also had to add. It looks like this:

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an absolute path.
; curl.cainfo = "d:\dev\xampp\apache\bin\curl-ca-bundle.crt"
```

Note that your paths will be different. I've added mine for context. You can place the `curl-ca-bundle.crt` file in a different location, just make sure that the appropriate path is used in the `curl.cainfo` setting.

After that, just restart your Local site, and you should be in business.

![image](https://user-images.githubusercontent.com/12645132/91600773-865d7900-e936-11ea-80af-406eb5ee9649.png)


Windows 10, Local v5.7.2+408, Site: PHP 7.3.5, Nginx, MySQL 5.7.28

**Comment by dingman** [comment]
@daveromsey I have done what you suggested, however the issue still persists. TIA for any next steps.

**Comment by dingman** [comment]
Actually, I was mistaken. My update hadn't saved properly. Upon updating it, it seems like I'm making progress. I'll confirm once I have more updates.

**Comment by dingman** [comment]
Looks like that solved it! Great, thank you. I'll file a bug with LocalWP on this.

**Comment by dingman** [comment]
For reference: https://localwp.canny.io/bug-reports/p/self-signed-ssl-missing

**Comment by richaber** [comment]
I am leaving this ticket open for my own reference, while I work through a potential "out-of-the-box" solution in a try branch.

**Comment by richaber** [comment]
We should document this in the wiki in #90 (if we get that in progress before the "try" branch I've been looking into for including our own cURL cert).

**Comment by garubi** [comment]
I can confirm that following the steps from https://github.com/WebDevStudios/wp-search-with-algolia/issues/87#issuecomment-683005495 I got it working
