### ISSUE TITLE
version discrep

### ISSUE THREAD

**Issue by dingman** [WebDevStudios/wp-search-with-algolia#92]
I'm reading through the changelog for 1.4.0 and I'm seeing this:

Updates instantsearch.js to 1.12.1 (last of the 1.x series)

However, their documentation references 4.x as latest. Was this a version typo or is it indeed still using 1.x instead of 4.x?

https://www.algolia.com/doc/guides/building-search-ui/installation/js/

**Comment by richaber** [comment]
Howdy @dingman,

That is correct, we updated instantsearch.js to [1.12.1](https://github.com/algolia/instantsearch.js/releases/tag/v1.12.1) (as seen in our [package-lock.json](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/package-lock.json#L260-L261)).

As stated in the WP Search with Algolia [1.4.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/1.4.0) release notes:

- Update Algolia PHP Search Client to version 2.7.0.
- Update Algolia JS libraries to most recent compatible (non-breaking) versions
    - Updates autocomplete.js to 0.37.1 (current release as of 2020-01-27)
    - Updates algoliasearch to 3.35.1 (last of the 3.x series)
    - Updates instantsearch.js to 1.12.1 (last of the 1.x series)

While upgrading the Algolia PHP Search Client to the most recent version, which entailed minimal risk to WP Search with Algolia users, we also updated the Algolia JS libs to their most recent, _compatible_, _non-breaking_ versions.

We were _not yet ready_ to upgrade the JS libraries to MAJOR releases, due to _incompatible breaking changes_, which would entail a little more risk.

That's probably a little more apparent in the WPORG changelog, where the additional indentation seems to make that a little more obvious. I should have checked the indentation in the Github release notes to ensure they indented correctly when I released that version.

**Comment by richaber** [comment]
Howdy @dingman,

I do not know if you've been following along with the WPSWA 2.0.0 activity, but we have just released version 2.0.0, which updates the bundled Algolia libraries.

* Update Algolia JavaScript API Client to 4.10.3
* Update Algolia InstantSearch.js to 4.25.2
* Update Algolia Autocomplete.js to 0.38.0
* Update Algolia PHP API Client to 3.0.2

https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0

https://plugins.svn.wordpress.org/wp-search-with-algolia/tags/2.0.0/
